#ifndef RESOURCE_H
#define RESOURCE_H

#include <QString>
#include <QIcon>
#include <QDateTime>
#include "globals.h"

class gameproject;
class gcresource
{

public:
    gcresource();
    QString
        name,       // resource name
        path,       // virtual path resource is placed
        type;       // The resource type, used to determine which editor to be used

    /* Example about `type`:

            This variable is used if same type of resource must be edited by different
            resource editors. For example, a class can be:

                1. Generated by some Wizard/widget
                2. Default piGameCreator class (event-based)
                3. Raw piGameScript class (100% code in one GameScript file)

            In this case, the "type" will contain different values that will determine the editor used to create and edit this class.
            The class resource itself must contain normal compilable PGS file so even users that do not have
            the proper editor widget can still open the class as eventbased or codebased
     */

    QIcon icon;     // resource icon for the trees and lists
    QPixmap preview; //resource thumbnail

    QStringList sourceFiles;    //Used for resource reloading when file changes
    QStringList dependencies;   //Used for exporting or sharing

    virtual bool checkSourceFiles();    //checks all source files and reloads them if needed

    virtual QString relativeFolder();   //returns the resource's folder
    virtual QString fileName();         //returns the resource file name
    virtual QString mainFolderName();   //returns the main folder name
    virtual QString kind();             //returns the resource kind

    virtual bool addToProject(gameproject* p);

    // Team Collaboration Server / Version control statuses - will not be used for now
    QString csLastEditedBy, csCreatedBy;    //usernames
    QDateTime csServerTime, csLocalTime;    //timestamps
    bool csIsDownloaded;
};

#endif // RESOURCE_H
